import 'profile.dart';

final List<Profile> profiles = [
  Profile(
    id: 1,
    name: 'Dwiky',
    nim: '231535',
    kelas: '4A',
    sd: 'SD 4',
    smp: 'SMP N 1',
    smk: 'SMK N 1',
    kampus: 'Politeknik',
    image: 'assets/images/images.png',
    background: 'assets/images/nature.webp',
  ),
  Profile(
    id: 2,
    name: 'Adit',
    nim: '231536',
    kelas: '4B',
    sd: 'SD 5',
    smp: 'SMP N 2',
    smk: 'SMK N 2',
    kampus: 'Politeknik',
    image: 'assets/images/adit_profil.jpeg',
    background: 'assets/images/adit_bg.jpg',
  ),
  Profile(
    id: 3,
    name: 'Sopo',
    nim: '231537',
    kelas: '4B',
    sd: 'SD 5',
    smp: 'SMP N 2',
    smk: 'SMK N 2',
    kampus: 'Politeknik',
    image: 'assets/images/sopo_profil.jpg',
    background: 'assets/images/sopo_bg.jpg',
  ),
  Profile(
    id: 4,
    name: 'Jarwo',
    nim: '231538',
    kelas: '4B',
    sd: 'SD 5',
    smp: 'SMP N 2',
    smk: 'SMK N 2',
    kampus: 'Politeknik',
    image: 'assets/images/jarwo_profil.jpg',
    background: 'assets/images/jarwo_bg.jpg',
  ),
  Profile(
    id: 5,
    name: 'Denis',
    nim: '231539',
    kelas: '4B',
    sd: 'SD 5',
    smp: 'SMP N 2',
    smk: 'SMK N 2',
    kampus: 'Politeknik',
    image: 'assets/images/denis_profil.png',
    background: 'assets/images/denis_bg.jpg',
  ),
  // ...tambahkan profil lain sesuai kebutuhan...
];
